artifact_location: /home/ubuntu/project/amphgt_refactor/out_pretrain/mlflow_tracking/868022504758860728
creation_time: 1729869445370
experiment_id: '868022504758860728'
last_update_time: 1729869445370
lifecycle_stage: active
name: Pretraining_FraSCESS
