artifact_uri: /home/ubuntu/project/amphgt_refactor/out_pretrain/mlflow_tracking/868022504758860728/dcd2785ef3d547adbf54f51fe81fff1a/artifacts
end_time: 1729870935929
entry_point_name: ''
experiment_id: '868022504758860728'
lifecycle_stage: active
run_id: dcd2785ef3d547adbf54f51fe81fff1a
run_name: thoughtful-fly-463
run_uuid: dcd2785ef3d547adbf54f51fe81fff1a
source_name: ''
source_type: 4
source_version: ''
start_time: 1729869452368
status: 4
tags: []
user_id: ubuntu
