train:
  seed: 42
  log_interval: 5  # Log every 100 steps
  # val_interval: 1000
  cuda_deterministic: False
  batch_size: 128
  hid_dim: 300
  act: "relu"
  depth: 5
  num_task: 1
  atom_dim: 42 # do not change
  bond_dim: 14 # do not change
  pharm_dim: 196 # do not change
  reac_dim: 14
  num_layer: 5
  num_tasks: 1
  frag_method: "FraSCESS"
  train_tag: "s3_inference"
  load_pretrained: True # if not, train from scratch on finetune data
  readout: "att" # "att": HierAttnReadout, "gru": GRUReadout, "": no readout
  pooling: "mean" # works when not gru/att readout, mean, max, sum
  checkpoint_path: out_finetune_binary/02-22-09-45/checkpoint_epoch_8_best/model.pt

data:
  vocablist: tokenizer/vocablist/vocab_1.json
  test_sdf_pos: datasets/positive_indetest_2567.smi
  test_sdf_neg: datasets/negative_indetest_1837.smi
  tmp_dir: ./tmp/finetune_binary
  chunk_size: 2000
  # save_path: "/home/ubuntu/project/amphgt_refactor/datasets/split/pretrain"
  num_workers: 2

logger:
  log: True
  log_dir: "${output_dir}/${now:%m-%d-%H-%M}"
  test_run: False

mode:
  nni: false  # If using NNI for hyperparameter tuning
  ddp: false   # Distributed Data Parallel mode