train:
  seed: 42
  log_interval: 5  # Log every 100 steps
  val_interval: 1000
  cuda_deterministic: False
  mask_edge: False
  mask_atom: True
  mask_fragment: True
  mask_rsd: True
  mask_rate: 0.6 # how many elements in a peptide should be masked.
  batch_size: 16
  hid_dim: 512
  act: "relu"
  depth: 5
  # num_task: 1
  atom_dim: 42 # do not change
  bond_dim: 14 # do not change
  pharm_dim: 196 # do not change
  rsd_dim: 512
  reac_dim: 14
  num_layer: 5
  lr: 0.001
  decay: 0
  epochs: 10
  patience: 5
  frag_method: "FraSCESS"
  train_tag: "s1_pretrain"
  decoder_type: "MLP" # MLP, HGC, HAN

data:
  vocablist: tokenizer/vocablist/vocab_1.json
  train_sdf: datasets/test_new.smi
  valid_sdf: datasets/test_new.smi
  test_sdf: datasets/test_new.smi
  tmp_dir: ./tmp/pretrain
  chunk_size: 2000
  # save_path: "/home/ubuntu/project/amphgt_refactor/datasets/split/pretrain"
  num_workers: 2

logger:
  log: True
  log_dir: "${output_dir}/${now:%m-%d-%H-%M}"
  log_per_steps: 5
  tracking_uri: "${output_dir}/mlflow_tracking"
  mlflow_exp_name: "Pretraining_FraSCESS"
  test_run: True

mode:
  nni: false  # If using NNI for hyperparameter tuning
  ddp: false   # Distributed Data Parallel mode