train:
  seed: 42
  log_interval: 5  # Log every 100 steps
  val_interval: 1000
  cuda_deterministic: False
  mask_edge: False
  mask_atom: True
  mask_fragment: True
  mask_rate: 0.5 # how many atoms in a peptide should be masked.
  batch_size: 64
  hid_dim: 300
  act: "relu"
  depth: 5
  # num_task: 1
  atom_dim: 42 # do not change
  bond_dim: 14 # do not change
  pharm_dim: 196 # do not change
  reac_dim: 14
  num_layer: 5
  lr: 0.001
  decay: 0
  epochs: 10
  frag_method: "FraSCESS"
  train_tag: "s1_pretrain"
  decoder_type: "HGC"

data:
  vocablist: G:\AmpHGT\refactor\amphgt_refactor\tokenizer\vocablist\vocab_1.json
  train_sdf: G:\AmpHGT\refactor\amphgt_refactor\datasets\positive_train_9924.smi
  valid_sdf: G:\AmpHGT\refactor\amphgt_refactor\datasets\positive_val_2480.smi
  test_sdf: G:\AmpHGT\refactor\amphgt_refactor\datasets\XU_AMP.smi
  tmp_dir: .\tmp\pretrain
  chunk_size: 10000
  # save_path: "/home/ubuntu/project/amphgt_refactor/datasets/split/pretrain"
  num_workers: 2

logger:
  log: True
  log_dir: "${output_dir}/${now:%m-%d-%H-%M}"
  log_per_steps: 5
  tracking_uri: "${output_dir}/mlflow_tracking"
  mlflow_exp_name: "Pretraining_FraSCESS"
  test_run: True

mode:
  nni: false  # If using NNI for hyperparameter tuning
  ddp: false   # Distributed Data Parallel mode